version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'master'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'
    groups:
      github-actions-major:
        update-types:
          - 'major'
      github-actions-minor:
        update-types:
          - 'minor'
      github-actions-patch:
        update-types:
          - 'patch'

  # Maintain dependencies for NPM
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'master'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'
    groups:
      npm-minor:
        update-types:
          - 'minor'
      npm-patch:
        update-types:
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Maintain dependencies for Docker
  - package-ecosystem: 'docker'
    directory: '/'
    target-branch: 'master'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'
    groups:
      docker-minor:
        update-types:
          - 'minor'
      docker-patch:
        update-types:
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
