version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'master'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'

  # Maintain dependencies for NPM
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'master'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'

  # Maintain dependencies for Docker
  - package-ecosystem: 'docker'
    directory: '/'
    target-branch: 'master'
    schedule:
      interval: 'monthly'
    assignees:
      - 'derogab'
    labels:
      - 'dependencies'
