# Volumes are used to persist data between container restarts
volumes:
  poop-cleaner-data:

# Networks are used to connect containers
networks:
  poop-cleaner-network:
    name: poop-cleaner-network
    driver: bridge

# Services are the containers that will be run
services:
  # Poop Cleaner Data Service
  poop-cleaner-data:
    restart: always
    container_name: poop-cleaner-data
    image: redis:7.2.4-alpine
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - poop-cleaner-data:/data
    networks:
      - poop-cleaner-network  
  # Poop Cleaner App Service
  poop-cleaner-app:
    restart: always
    container_name: poop-cleaner-app
    build: .
    environment:
      - REDIS_HOST=poop-cleaner-data
      - REDIS_PORT=6379
    env_file:
      - .env
    networks:
      - poop-cleaner-network 
